CERTCC/SSVC

- doc/version_1/040_treesForVulMgmt.md
Proposed fix for #16, just converting to active voice to clarify slow vs rapid virulence/automatability
> rephrase kill chain automation text to active voice

- doc/version_1/040_treesForVulMgmt.md
Fix #13 
Adds a paragraph to scope giving an example of how suppliers and deployers might have different positions on whether EOL software is in or out of scope.
> Address EOL products in scope section

- .gitignore
- data/ssvc_2_deployer.csv
- data/ssvc_2_deployer_simplified.csv
- data/ssvc_2_supplier.csv
- data/ssvc_2_supplier_simplified.csv
- doc/version_1/040_treesForVulMgmt.md
Fixes #1 
Squashed commits:
[07497bd] compress SafetyImpact into PublicSafetyImpact
[6b9c932] ignore a helper xlsx file
[576f968] reset inadvertent change
[419349d] remove index on supplier csv (+1 squashed commit)
Squashed commits:
[6486a57] add full supplier csv
[6918107] remove index on simplified csv (+1 squashed commit)
Squashed commits:
[1845f90] add simplified csv
[7d07685] add combined safety/mission impact column
[52dd62a] remove duplicates after collapsing from 5-4. Keep highest outcome
[898a082] collapse two lowest mission and safety impacts into one level each and remove duplicates
[b344dea] remove row indices (make future diffs cleaner)
[420559c] copy csv files for version 2
[d07e953] fix some straggling Applier / Developers (+2 squashed commits)
Squashed commits:
[878a91d] …
> Compress safety and mission impacts fix for #1 (+11 squashed commits)

- doc/version_1/047_treesForVulMgmt_4.md
This should fix #25. I've basically written the abbreviated format (that is, vector string) from scratch, since what SSVCv1 had in the "Pilot results" subsection in Section 5 was not particularly descriptive. 
There are other issues associated with #24 that this commit creates a space to resolve. Those are tagged in the text, namely #26  and #29.  
In the process of working on this, it also raised the issue of what sort of full format we may want to specify for communicating results. I'll create a new issue for that.
> Started comms guidance; vector string notation rewrite

- ssvc-calc/ssvc.js
Simple v1 or v2 detector script ensures that CSV files can optionally have Row-ID column, made of numbers.  The javascript checks to see if variable y[0][0] is a number, i.e. the first column element of the second row of CSV file (first row is assumed to be the header)
Vijay
> Use simple number search to detect v1 vs v2 CSV trees

- doc/md_src_files/065_changelog.md
- doc/md_src_files/120_acks.md
> Section for changelog based on closed issues

- data/csvs/README
- data/csvs/deployer-options_v2.csv
- data/csvs/supplier-options_v2.csv
- src/enumerate-deployer-options.sh
- src/enumerate-supplier-options.sh
contributes to #160 
I used the PDFs in doc/graphics to type in the priority labels. Hopefully there are no typos in the priority labels -- I don't see any. The decision point combinations are programmatically generated using the enumerate*.sh scripts, so the names for the decision point values are consistent since the script creates those.
> recreated CSV files and added a folder for them with readme; updated generation scripts

- doc/compile-html-citeproc.sh
- doc/compile-pdf.sh
- doc/emoji-replacements.sed
- doc/pdf-styling.yaml
This just provides the tools to create a new PDF from the markdown. Before creating a new PDF, want to check on the version numbering used in line 25, which is major.minor_date rather than proper semver, because then we don't have to make the script track git commits to the markdown in the doc folder. There is no special formatting to the PDF, it is a basic KOMA report template. 
I'd also like to make sure somone else can run the pandoc script. I think the requirements are pandoc and texlive. How should these be documented? 
If we can get it down to being as simple as running the script, we can ask for an updated PDF with every commit that changes the doc directory. 
Once this is settled, then we can have a different branch for adding an updated PDF.
> Pdf update

- doc/md_src_files/055_decision-points_2.md
As discussed in https://github.com/CERTCC/SSVC/pull/187.
> Updated the Mission Impact values

- ssvc-calc/Deployer-v2.0.0.json
According to the documentation on https://github.com/CERTCC/SSVC/blob/main/doc/md_src_files/055_decision-points_2.md#mission-impact "none" and "degraded" are actually just one option called "None/ Non-Essential Degraded".
> Fixed redundant option for Mission Impact

- doc/md_src_files/060_decision-trees.md
- doc/style-guide-how-to
> Add detail about customization, tree sharing, and decision point scope

- doc/md_src_files/060_decision-trees.md
The paragraph about tree versioning was buried inside the _Parsimony_ section, just calling it out with its own heading.
> add subsubsection header for tree versioning

- data/csvs/coord-triage-options.csv
- doc/graphics/ssvc_2_coord-triage.tex
- src/enumerate-coord-triage-options.sh
- ssvc-calc/Coordinator-Triage.json
fixes #266 
Makes Coordinator Triage `.csv`, tree diagram, `.sh`, and `.json` representation consistent with the main document's use of **Minimal** and **Significant** as the values of _Public Safety Impact_ rather than **Minor** and **Huge**.
> Make Public Safety Impact values consistent throughout

- src/analyze_csv.py
The column formerly known as "outcome" is now "priority" in the `.csv` files, so this change adjusts the default column it's looking for to match.
> Update analyze_csv.py to reflect csv column name changes

- data/schema/SSVC_Computed.schema.json
- data/schema/SSVC_Provision.schema.json
I fixed some typos in the computed and provision JSON schemas.
> fix typos in json schema descriptions

- docs/adr/0003-ssvc-decision-point-versioning-rules.md
- docs/adr/0006-ssvc-decision-point-versioning-rules.md
This PR updates the decision point versioning rules to reflect the discussion on PR #343 that led to Issue #367. It also adapts a format consistent with that of PR #368 w.r.t. the versioning rules presentation.
Doing this as a PR against another PR #368 for the sake of ADR number sequencing.
In the event that PR #368 is rejected, this change should be re-targeted at `main`.
- resolves #367
> Clarify Decision Point Versioning rules (revises ADR 0003 into ADR 0006)

- docs/adr/0003-ssvc-decision-point-versioning-rules.md
- docs/adr/0004-ssvc-decision-point-groups-are-versioned.md
- docs/adr/0005-ssvc-decision-point-group-versioning.md
- docs/adr/0006-ssvc-decision-point-versioning-rules.md
- docs/adr/index.md
This PR adds two ADRs:
- 0004 - SSVC Decision Point Groups are Versioned using SemVer
- 0005 - SSVC Decision Point Group Versioning Rules
As with #350, I separated these out so that the decision _that they are versioned_ is distinct from the _versioning rules_.
It is my intent that existing decision point groups already present in the python code should be consistent with these rules. However, the rules were developed during the process of creating the python code, and written down afterwards. So any discrepancy is basically the result of an out-of-order operation. We should correct any such discrepancies we detect, of course, whether by modifying the code to match the rules, or perhaps adjusting the rules if there's a good reason to do so.
- resolves #355
> Add Decision Point Group Versioning ADRs

- .github/workflows/python-app.yml
Now that we have a pyproject.toml, we can verify that the build process works too, and upload artifacts from each run
Artifact retention is set to 14 days
> Add build steps to python-app.yml

- docs/reference/code/outcomes.md
- docs/reference/code/policy_generator.md
- mkdocs.yml
- requirements.txt
- src/ssvc/_mixins.py
- src/ssvc/csv_analyzer.py
- src/ssvc/decision_points/base.py
- src/ssvc/dp_groups/base.py
- src/ssvc/outcomes/__init__.py
- src/ssvc/outcomes/base.py
- src/ssvc/outcomes/groups.py
- src/ssvc/policy_generator.py
- src/test/test_csv_analyzer.py
- src/test/test_dp_base.py
- src/test/test_dp_groups.py
- src/test/test_outcomes.py
- src/test/test_policy_generator.py
This PR contains a python class that generates an SSVC decision policy (aka a "tree") that fully enumerates a set of decision points and their values, and assigns an outcome to each input value tuple. It does so by 
- constructing a partial order over all the input value tuples
- generating a topological sort over the resulting partial order
- assigning outcomes according to a set of provided weights
- emitting a CSV that replicates the format we've previously used to represent decision policies
- (one column for each decision point, plus an outcome column filled in with the assignments made)
If you run `policy_generator.py` directly, it outputs a policy that's rather close to the Deployer 2.1 tree.
At this point, my goal is to get the module in place with this PR. 
We will need to figure …
> Policy Generator tool, first pass

- docs/howto/bootstrap/collect.md
- docs/howto/bootstrap/use.md
- docs/howto/communicating_results.md
- docs/howto/coordination_decisions.md
- docs/howto/coordination_intro.md
- docs/howto/coordinator_trees.md
- docs/howto/index.md
- docs/howto/tree_customization.md
- mkdocs.yml
This PR reorganizes the HowTo section
- merge Evidence Gathering and Collect pages
- merge Communicating Results and Use pages
- refactor Coordinator decisions to bring disparate pieces together into a cohesive subsection
- add / fix headings and nav 
- resolves #378
- unblocks #372 
As this is primarily a content reorganization, I did not attempt to edit the existing content. That _will_ need to be done, but this PR isn't the place for it.
The staging server is caught up to https://github.com/CERTCC/SSVC/pull/379/commits/82a302e911b150936939000ae8e605364dec780c
https://certcc.github.io/SSVC-staging/howto/
> Reorganize HowTo section

- src/ssvc/policy_generator.py
PolicyGenerator's internal checking of all paths is overzealous when the graph of input states gets large, which it can do very easily with just a few decision points. The resulting list of paths in nx.all_simple_paths grows very rapidly, which causes the whole thing to slow down if this feature is activated. This PR retains the option to do the validation if desired by setting the `validate=True` option when a PolicyGenerator object is created. But the default behavior is now to not look at every path. This should be ok, because the way we're creating the graph as the transient reduction of a graph that only adds edges where needed should be sufficient to ensure that we're not going to get any bogus paths anyway.
> Fix policygenerator slowness

- src/ssvc/decision_points/safety_impact.py
- src/test/test_cvss_helpers.py
> Two small typofixes

- docs/index.md
- mkdocs.yml
- requirements.txt
Currently staged at https://certcc.github.io/SSVC-staging/
This PR adds:
- intro paragraph on site home page
- a 4x4 grid to direct folks from the home page to the various sections of the site
- upgrades mkdocs-material to the latest release
- fixes a deprecation warning about obsolete mkdocs extensions
> Add grid to homepage

- .github/dependabot.yml
It's useful to have dependabot keep our github actions up to date.
This is already working in https://github.com/CERTCC/Vultron/blob/main/.github/dependabot.yml
> Add GH actions to dependabot config

- src/ssvc/outcomes/groups.py
> Add OutcomeGroup for TheParanoids PrioritizedRiskRemediation

- docs/about/changelog.md
This PR removes all links in `docs/about/changelog.md`.
Rationale: Adding links to `docs/about/changelog.md` seems like it was a mistake. As the documentation changes, and especially as pages move around and section headings change, the links in the changelog that were specific to that version will tend to rot over time. For example, if we merge #451, then the links in `docs/about/changelog.md` to the abbreviated format docs have nowhere to go, so we'd just have to remove them anyway.
My preference would be that we just keep `docs/about/changelog.md` as text without cross-linking it at all.
A potential compromise would be that we only maintain links to the latest "release", in which case we could rollback the change currently suggested for lines 3-21 for now. Then we'd need to eliminate …
> Unlink text in changelog.md

- docs/howto/communicating_results.md
- docs/topics/future_work.md
This PR removes the "abbreviated format" aka "vector format" from the documentation.
- ran into this while working on #443
- resolves #333
> Remove abbreviated format from docs

- mkdocs.yml
This PR is a one-liner that changes the title string in the site header from "SSVC" to "SSVC: Stakeholder-Specific Vulnerability Categorization"
> Expand SSVC acronym in site name

- .github/workflows/link_checker.yml
Now that we know it works, we should run linkchecker every time the main branch is updated (this is in addition to running it on all PRs, which is how it was configured after #465)
- extends #465
> Make `link_checker.yml` run automatically on push to `main`

- data/json/decision_points/report_credibility_1_0_0.json
- data/json/decision_points/report_public_1_0_0.json
- docs/_generated/decision_points/report_credibility_1_0_0.md
- docs/_generated/decision_points/report_public_1_0_0.md
- src/ssvc/csv_analyzer.py
- src/ssvc/decision_points/report_credibility.py
- src/ssvc/decision_points/report_public.py
- src/ssvc/policy_generator.py
- src/test/test_csv_analyzer.py
- src/test/test_policy_generator.py
This PR 
- adds some topological sort checks to the csv analyzer and policy generator scripts.
- reorders the `report public` and `report credibility` decision points to match expected directionality of values
These features were added after I noticed that report public and report credibility were improperly ordered according to the policy generator assumption that decision points are ordered from lowest-to-highest along a dimension that correlates to "likely to act".
> Add topo sort to csv analyzer and policy generator

- docs/_includes/helping_out.md
This PR:
- resolves #401 by adding a link to the Github Tips wiki page https://github.com/CERTCC/SSVC/wiki/Github-Tips-for-SSVC-contributors in `docs/_includes/helping_out.md` 
Note: `docs/_includes/helping_out.md` is included in the SSVC home page, the community engagement page, and the contact us page.
> Add link to github tips wiki page

- docs/howto/bootstrap/prepare.md
- docs/index.md
- docs/topics/items_with_same_priority.md
This request is to address https://github.com/CERTCC/SSVC/issues/493 and https://github.com/CERTCC/SSVC/issues/381.
Its showing I modified index.md but the change is the same. 
- resolves #493 
- resolves #381
> Ccullen cert patch 2

- docs/tutorials/index.md
- mkdocs.yml
This PR adds a small blurb for the calculator on the Learning home page. See screenshot.
> Add Calculator blurb to `Learning SSVC`

- docs/topics/risk_tolerance_and_priority.md
This PR 
- updates the ISO 73:2009 ref to ISO 31073:2022 which superseded it
- inlines the two references on the page (using links instead of footnotes)
- adjusts vertical spacing so sidebars don't overlap
> Update references in Risk Tolerance

- docs/topics/information_sources.md
Based on discussion in #284 , I believe this should close #284 if merged.
> draft of update for cvss v4

- .github/workflows/deploy_site.yml
This PR changes `.github/workflows/deploy_site.yml` so that it will run on pushes to the `publish` branch. This is needed so that we can deploy the new site to `certcc.github.io/SSVC`
> Set up site deployment on publish branch

- mkdocs.yml
This PR activates the mkdocs features that will cause the sitemap.xml file to be populated.
https://certcc.github.io/SSVC/sitemap.xml
see for contrast
https://certcc.github.io/Vultron/sitemap.xml
Why sitemap.xml is important: https://developers.google.com/search/docs/crawling-indexing/sitemaps/overview
> Configure sitemap.xml to be populated

- data/csvs/child_trees/human-impact.csv
- docs/ssvc-calc/Deployer.json
- docs/ssvc-calc/css.css
From Issue #123  feedback add keys to the JSON Deployer.json in ssvc-calc to allow for ease of creating SSVC Vector strings.
> i18n improvement to Deployer.json

- docs/howto/coordination_intro.md
- docs/howto/coordination_triage_decision.md
- docs/howto/publication_decision.md
We just launched the latest CVD guide at https://certcc.github.io/CERT-Guide-to-CVD/
This PR changes the links from the Confluence version of the Guide to the new github.io version.
- resolves #561
> Replace vuls.cert.org CVD guide links with certcc.github.io links

- Dockerfile
- README.md
This PR adds a Dockerfile that installs the requirements and runs the included unit tests.
Usage:
```bash
$ docker build -t ssvc_test .
...
$ docker run -it --rm ssvc_test 
............................................................ [100%]
60 passed in 0.71s
```
I'd like to eventually dockerize the dev server too, but that will come later.
> Dockerize unit tests

- src/ssvc/policy_generator.py
- fixes #590 
`AUTOMATABLE_1` went away at some point (becoming `VIRULENCE_1`) and so we need to use `AUTOMATABLE_2` instead in the example code.
> Fix bad import in PolicyGenerator

- data/schema/v1/Decision_Point-1-0-1.schema.json
- data/schema/v1/Decision_Point_Value_Selection-1-0-1.schema.json
Looks like the id field on two of the schema files are garbled. These should be correct now.
> schema URL's ID field is garbled

- data/schema/v1/Decision_Point_Value_Selection-1-0-1.schema.json
This PR modifies the base url for the JSON schema to change from `draft-07` to `2020-12`
- https://json-schema.org/draft/2020-12/release-notes
Original text:
> This will be a good one to merge to Main and then finally publish with all the latest changes. I don't think any version  number changes are needed as the schema is entirely the same and works fine with both draft-07 and 2020-12 the same way.
> Vijay
> Change json schema base to 2020-12

- data/schema/v1/Decision_Point-1-0-1.schema.json
- data/schema/v1/Decision_Point_Group-1-0-1.schema.json
- data/schema/v1/Decision_Point_Value_Selection-1-0-1.schema.json
- change `definitions`to `$defs`
- fixes https://github.com/CERTCC/SSVC/issues/640#issuecomment-2504366097
> SSVC JSON Schema 2020-12

- data/schema/v1/Decision_Point_Value_Selection-1-0-1.schema.json
- data/schema_examples/CVE-1900-1234-Decision_Point_Value_Selection.json
Simple fix for the CVSS misspelled in schema definition.
> Spelling error fix in Decision Point Value Selection cvvs to cvss

- src/test/test_schema.py
The JSON schema unit tests were failing because the local path substitution wasn't working consistently across different environments. This PR fixes that by computing a relative path from the test file in which it is called.
> fix unit test

- src/ssvc/decision_points/automatable.py
- src/ssvc/decision_points/base.py
- src/ssvc/decision_points/critical_software.py
- src/ssvc/decision_points/helpers.py
- src/ssvc/decision_points/high_value_asset.py
- src/ssvc/decision_points/human_impact.py
- src/ssvc/decision_points/mission_impact.py
- src/ssvc/decision_points/mission_prevalence.py
- src/ssvc/decision_points/public_safety_impact.py
- src/ssvc/decision_points/public_value_added.py
- src/ssvc/decision_points/report_credibility.py
- src/ssvc/decision_points/report_public.py
- src/ssvc/decision_points/safety_impact.py
- src/ssvc/decision_points/supplier_cardinality.py
- src/ssvc/decision_points/supplier_contacted.py
- src/ssvc/decision_points/supplier_engagement.py
- src/ssvc/decision_points/supplier_involvement.py
- src/ssvc/decision_points/system_exposure.py
- src/ssvc/decision_points/technical_impact.py
- src/ssvc/decision_points/utility.py
- src/ssvc/decision_points/value_density.py
Standardize docstrings to define what the program does, add missing license wording, and format blank lines around header docstrings.
- resolves #678
> Resolve Issue 678

- data/schema_examples/Computed-CVE-2014-0751-Coordinator-with-tree.json
- data/schema_examples/Computed-CVE-2014-0751-Coordinator.json
- requirements.txt
- src/ssvc/decision_points/mission_prevalence.py
> Fix json schema example

- requirements.txt
- src/ssvc/_mixins.py
- resolves #347 
This PR takes advantage of our switch to pydantic data classes in #674 to add a field validator on the `_Versioned` mixin class that enforces valid semver strings in the`version` attribute.
This pull request includes updates to the `src/ssvc/_mixins.py` file to improve version validation by adding a new dependency and a validation method.
Validation improvements:
* [`src/ssvc/_mixins.py`](diffhunk://#diff-3e266c8592982d40cd5b33b96e21eaa4399524f834f5d2a239c0a5e0e65fc788L20-R21): Added `semver` library import to handle version parsing and validation.
* [`src/ssvc/_mixins.py`](diffhunk://#diff-3e266c8592982d40cd5b33b96e21eaa4399524f834f5d2a239c0a5e0e65fc788R34-R50): Introduced a `validate_version` method in the `_Versioned` class using `field_validator` to ensure the …
> Add semantic versioning validator to _Versioned mixin

- docs/reference/decision_points/cvss/index.md
- docs/reference/decision_points/cvss/qualitative_severity.md
- mkdocs.yml
- src/ssvc/decision_points/cvss/qualitative_severity.py
- src/ssvc/doc_helpers.py
- resolves #711, adding CVSS categories (Low, Medium, High, Critical) for use in future decision models
- adds an `include_json:bool` option (defaults to `True`) on the `example_block()` method so that docs can ask for a defined decision point block without the `json` example being included (by explicitly passing `include_json=False`)
- also fixed a small bug where `example_block()` accepted but did not use an `indent:int` parameter
This pull request introduces a new decision point for the [CVSS Qualitative Severity Rating Scale](https://www.first.org/cvss/v4.0/specification-document#Qualitative-Severity-Rating-Scale) and updates the documentation accordingly. The most important changes include adding the new decision point, updating the documentation to include it, and modifying helper …
> Add CVSS Qualitative Severity Rating Scale decision point

- data/json/decision_points/cvss/automatable_1_0_0.json
- data/json/decision_points/cvss/availability_impact_to_the_subsequent_system_1_0_0.json
- data/json/decision_points/cvss/availability_impact_to_the_vulnerable_system_3_0_0.json
- data/json/decision_points/cvss/confidentiality_impact_to_the_vulnerable_system_3_0_0.json
- data/json/decision_points/cvss/integrity_impact_to_the_vulnerable_system_3_0_0.json
- data/json/decision_points/cvss/integrity_requirement_1_1_1.json
- data/json/decision_points/cvss/modified_availability_impact_to_the_subsequent_system_1_0_0.json
- data/json/decision_points/cvss/modified_availability_impact_to_the_vulnerable_system_3_0_0.json
- data/json/decision_points/cvss/modified_confidentiality_impact_to_the_vulnerable_system_3_0_0.json
- data/json/decision_points/cvss/modified_integrity_impact_to_the_vulnerable_system_3_0_0.json
Forgot to run doctools.py after we modified some of the decision points. This only affects the examples in the `/data/json/decision_points` dir in the repository, the site now generates the reference examples on the fly because of #683
> Update json examples in repository

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/question.md
- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
- .github/workflows/deploy_site.yml
- data/json/decision_points/cvss/automatable_1_0_0.json
- data/json/decision_points/cvss/availability_impact_to_the_subsequent_system_1_0_0.json
- data/json/decision_points/cvss/availability_impact_to_the_vulnerable_system_3_0_0.json
- data/json/decision_points/cvss/confidentiality_impact_to_the_vulnerable_system_3_0_0.json
- data/json/decision_points/cvss/integrity_impact_to_the_vulnerable_system_3_0_0.json
- data/json/decision_points/cvss/integrity_requirement_1_1_1.json
- data/json/decision_points/cvss/modified_availability_impact_to_the_subsequent_system_1_0_0.json
- data/json/decision_points/cvss/modified_availability_impact_to_the_vulnerable_system_3_0_0.json
- data/json/decision_points/cvss/modified_confidentiality_impact_to_the_vulnerable_system_3_0_0.json
- data/json/decision_points/cvss/modified_integrity_impact_to_the_vulnerable_system_3_0_0.json
- requirements.txt
This is a quick patch to fix a post-deployment bug in the python path when the site tries to build.
Examples are currently failing to render at site build time because mkdocs doesn't know where to find the `ssvc` module.
See change in `.github/workflows/deploy_site.yml`
Once deployed and we confirm it works, #729 should be closed
> Catch up publish to main

- .github/workflows/deploy_site.yml
This is a backport of a manual change to the publish branch subsequent to #731 to fix a typo (`;` &rarr; `:`)
> Fix deployment workflow

- .github/workflows/lint_md_changes.yml
On review of the recent `tj-actions/changed-files` [compromise](https://www.cisa.gov/news-events/alerts/2025/03/18/supply-chain-compromise-third-party-github-action-cve-2025-30066) we determined that while the `.github/workflows/lint_md_changes.yml` did point to one of the affected tags, the workflow does not involve any secrets so there was no impact to the project.
However, in the interest of protecting against any future regression, this PR pins the action to a specific sha1 hash instead of a version tag, as the version tags were also compromised in the above incident.
See original issue in tj-actions/changed-files#2463
> Pin tj-actions/changed-files action to a specific sha1

- data/schema/v1/Decision_Point-1-0-1.schema.json
- data/schema/v1/Decision_Point_Group-1-0-1.schema.json
- data/schema/v1/Decision_Point_Value_Selection-1-0-1.schema.json
- data/schema/v1/Outcome_Group-1-0-1.schema.json
- docs/about/copyright.md
- src/ssvc/_mixins.py
- src/ssvc/namespaces.py
- src/test/test_mixins.py
This is quick PR to try to get CSAF workflow completed and resolve #764 and related PR in CSAF https://github.com/oasis-tcs/csaf/pull/914 and related Issue https://github.com/oasis-tcs/csaf/issues/803
> Attempt to resolve #764 into Publish branch for updates.

- Makefile
- README.md
- docker/Dockerfile
- docker/docker-compose.yml
This PR refactors our use of `make` and `docker` to use `docker-compose`, which simplifies the process for building and running container images. This will be useful as a foundation for future architectures where we need to spin up more containers for microservices, as we begin to address things like #655.
This pull request refactors the project's Docker setup to simplify workflows and improve maintainability. Key changes include replacing individual `Makefile` Docker commands with `docker-compose` commands, reorganizing Docker-related files into a dedicated `docker` directory, and updating documentation to reflect these changes.
* **Makefile Changes**: Removed individual Docker build and run targets (`dockerbuild_test`, `dockerrun_test`, `dockerbuild_docs`, `dockerrun_docs`) in favor of …
> Simplify Makefile / Dockerfile interactions using docker-compose.yml

- data/json/decision_tables/cisa/cisa_coordinate_dt_2_0_3.json
There is an error in the `data/json/decision_tables/cisa/cisa_coordinate_dt_2_0_3.json` which includes text from the output of .py run, that has been removed now.
Should be simpler to review!
> Fix CISA Decision Tree extra text remove

- data/json/decision_tables/ssvc/coordinator_publish_decision_table_1_0_0.json
- data/json/ssvc_object_registry.json
- src/ssvc/decision_tables/ssvc/coord_pub_dt.py
I think I got this right. The default generated mapping was pretty close, and I only had to change one or two outcome lines. It passes the check now. There are no changes to the content as published as a result, so I don't think we had a problem with this tree, not sure why it didn't work on a previous attempt (ref: #842)
This pull request adds a new decision table for coordinator publication prioritization to the SSVC (Stakeholder-Specific Vulnerability Categorization) data model. The new table, along with its supporting metadata, is now available in the object registry, enabling its use in decision support workflows.
**New Coordinator Publish Decision Table:**
* Added the `Coordinator Publish Decision Table` version 1.0.0 as `DT_COORD_PUBLISH` in both the data files and the SSVC object …
> Add Coordinator Publish DecisionTable

- docs/ssvc-calc/ssvc.js
This SSVC Calculator update will now accept the latest schema from Decision Tables as represented in schema version 2.0.0
> SSVC Cacluator to accept new schema

- docker/docker-compose.yml
Remove a default `volume` mount configuration from `docker-compose.yml` because it was causing bad interactions between the host system and the container when `uv` would rebuild the environment within the container. The MacOS dev host was flagging python libraries as untrusted after running the containers.
(cherry picked from commit 51f345e9840ccd0eafb44e68b4a1032fa7ddc4d9)
This pull request makes small changes to the `docker/docker-compose.yml` file by removing the bind mount volumes from the `docs` and `registry_api` services. This means the application source code will no longer be mounted into these containers at runtime, likely to improve container isolation or deployment consistency.
> Remove default volume mount in docker-compose config

- data/schema/v2/Decision_Point_Group-2-0-0.schema.json
- docs/reference/code/decision_point_groups.md
- src/ssvc/dp_groups/base.py
- resolves #918 
This pull request deprecates the `DecisionPointGroup` class and related documentation, signaling that `DecisionTable` should be used for new development. The changes introduce clear warnings in the code, schema, and documentation to inform users about the deprecation and future removal plans.
Deprecation of `DecisionPointGroup`:
* Added deprecation notice to the `DecisionPointGroup` class docstring and constructor in `src/ssvc/dp_groups/base.py`, raising a `DeprecationWarning` when instantiated.
* Inserted a module-level warning in `src/ssvc/dp_groups/base.py` to inform users that `ssvc.dp_groups` is deprecated and to direct them to `ssvc.decision_tables`.
Schema and documentation updates:
* Updated the schema description in …
> Mark `ssvc.dp_groups.base` as deprecated

- data/json/decision_points/basic/probability_scale_in_5_weighted_levels_ascending_1_0_0.json
- data/json/decision_points/nist_800_30/probability_scale_in_5_weighted_levels_ascending_1_0_0.json
- data/json/ssvc_object_registry.json
- docs/reference/code/namespaces.md
- src/ssvc/decision_points/nist/__init__.py
- src/ssvc/decision_points/nist/base.py
- src/ssvc/decision_points/nist/sp800_30_r1_g.py
- src/ssvc/namespaces.py
- src/test/test_namespaces.py
This PR:
- resolves #907 
- resolves #908
- might address #909 but there is not enough detail in that issue to tell whether it does or not
- Explicitly calls out _RESERVED_ namespace strings:
- `invalid` and `x_invalid` are blocked from use
- `example` and `x_example` are reserved for examples and documentation
- `test` and `x_test` are reserved for tests
- adds a `nist` namespace
- refactors one of the probability-based decision points based on NIST 800-30 into the `nist` namespace
- this incidentally resolved a situation in which two identically named decision points were clobbering each other when we generated the `.json` files, hence what appears to be an unrelated change to data/json/decision_points/basic/probability_scale_in_5_weighted_levels_ascending_1_0_0.json
- revises the …
> Update namespace documentation

- src/ssvc/doc_helpers.py
- src/test/test_doc_helpers.py
This PR modifies the behavior when we render decision points as markdown tables. Instead of having `Name (key)`, now it will render `Name` and `Key` into separate columns.
Before:
After:
This pull request updates the markdown table formatting in the `src/ssvc/doc_helpers.py` file to improve clarity and completeness. The changes modify both the table row template and the table header to include a separate column for the key of each value.
Markdown table formatting improvements:
* Changed the `MD_TABLE_ROW_TEMPLATE` to include a separate "Key" column, so each row now displays the value's name, key, and definition individually.
* Updated the markdown table header and alignment to add the "Key" column, ensuring the header matches the new row format.
> Make value key its own column when rendering decision point examples

- requirements.txt
- src/ssvc/decision_points/example/humidity.py
- src/ssvc/decision_points/example/weather.py
- src/ssvc/decision_tables/example/to_play.py
We can use the _registered_ `example` namespace for examples. It is already set up with base classes for both `ExampleDecisionPoint` and `ExampleDecisionTable` so that it also avoids registering the decision points and tables in the registry.
This pull request refactors the example decision point and decision table implementations to use new base classes specific to examples, and updates the identifiers in the decision table mappings to match the new naming convention. The changes improve consistency and modularity in the example code.
**Refactoring to use example-specific base classes:**
* Replaced usage of `SsvcDecisionPoint` with `ExampleDecisionPoint` in `humidity.py` and `weather.py` to clarify the distinction between example and SSVC decision points. …
> Clean up examples
