- doc/version_1/040_treesForVulMgmt.md
Adding proposed text from #15 
Fixes #15
> add text for automatability and vul chaining

- doc/version_1/045_treesForVulMgmt_3.md
Attempting to fix #3. 2nd try, rebased onto latest main.
Note that this PR is built on PR #55 so either that one should be integrated first or, if both are acceptable this one will also fix #53 when merged.
Fixes #3, #53
Closes #55
> Fix for #3

- src/README.md
- src/SSVC_csv-to-latex.py
> Added python script to convert CSV files to latex for tree viz

- doc/version_1/040_treesForVulMgmt.md
- doc/version_1/sources_ssvc.bib
> added risk definition from ISO

- doc/version_1/047_treesForVulMgmt_4.md
> Described customization options

- doc/version_1/047_treesForVulMgmt_4.md
> added passage on dealing with partial information

- doc/version_1/042_treesForVulMgmt_2.md
> Better described Utility, differenting it from exploitation.

- doc/md_src_files/060_decision-trees.md
- doc/md_src_files/sources_ssvc.bib
> discuss changing information 

- doc/md_src_files/050_decision-points_1.md
- doc/md_src_files/055_decision-points_2.md
- doc/md_src_files/sources_ssvc.bib
fixes #27 
Because 27 is it's last part, closes #24
> Info sources 27

- doc/md_src_files/050_decision-points_1.md
- doc/md_src_files/060_decision-trees.md
- doc/md_src_files/082_relatedSystems.md
- doc/md_src_files/sources_ssvc.bib
> Fix33 automation

- doc/md_src_files/040_stakeholders-scope.md
fixes #76 
I broke up the text Chuck produced because I thought it improved flow.  
It seems like some white space got cleaned up and caused a bunch of spurious diffs. The only actual changes are in `### Deploying Patches `
> What happens after remediation

- doc/md_src_files/060_decision-trees.md
- src/analyze_csv.py
Proposed fix for #60 
Add content to describe tree quality considerations: feature selection, feature type, overfitting, and parsimony. Also describe how to apply permutation importance as a metric to identify potential problem areas.
I also added a python script to src to compute permutation importance for a CSV file.
> add detail about tree quality considerations

- doc/md_src_files/090_futureWork.md
- doc/md_src_files/100_limitations.md
- doc/md_src_files/110_conclusion.md
> Update closing sections

- doc/compile-citeproc.sh
- doc/graphics/ssvc_2_coord-publish.tex
- doc/graphics/ssvc_2_coord-triage.tex
- doc/graphics/ssvc_2_deployer_SeEUMss.tex
- doc/graphics/ssvc_2_supplier.tex
- doc/md_src_files/030_representingInformation.md
- doc/md_src_files/040_stakeholders-scope.md
- doc/md_src_files/050_decision-points_1.md
- doc/md_src_files/055_decision-points_2.md
- doc/md_src_files/060_decision-trees.md
- doc/md_src_files/070_evaluationDraftTrees.md
- doc/style-guide-how-to
> Make markdown of tables and figures more portable

- ssvc-calc/ssvc.js
A minor update is needed so the the final step in the decision tree is not hard coded to be called "Decision" but can be other words that are actually read from the JSON file that has the decision tree adhering to SSVC JSON schema.
That is the only change in this commit, but essential for the CVE-5 ADP Pilot so it is possible to send ADP tree to CVE JSON schema folks to validate.
Vijay
> Removing hard-coded final keyword and final outcome

- data/schema/SSVC_Computed_v2.03.schema.json
- data/schema/SSVC_Provision_v2.03.schema.json
- index.html
- ssvc-calc/CISA-Coordinator-v2.0.3.json
- ssvc-calc/SSVC_Computed_v2.03.schema.json
- ssvc-calc/SSVC_Provision_v2.03.schema.json
- ssvc-calc/Supplier-v2.0.0.json
- ssvc-calc/css.css
- ssvc-calc/index.html
- ssvc-calc/sample-ssvc.txt
- ssvc-calc/ssvc.js
- ssvc.js
Update address issue #160 and #163  for both updating the trees here and at democert.org site.
1. The updates also include some functional improvements.
2. Do not lis/display  not yet selected decision nodes in the decision tree.
3. Do mouseover for all options and highlight the mouseover text to the currently being seen option
4. Allow user to revert to earlier steps in the decision tree so the user can "roll-back" decision if needed
5. Pop-up screen for complex decisions should not become invisible when accidentally closed. Provide a way to return to show the cumulative scoring calculator.
Vijay
> Multiple updates 160,163

- src/ssvc_v2.py
> make the ssvc_v2.py file work with current CSV file names and columns

- data/schema/SSVC_Computed_v2.03.schema.json
- data/schema/SSVC_Provision_v2.03.schema.json
The version number in the file name and the URL seem to differ.
> fixed a typo

- doc/md_src_files/060_decision-trees.md
Resolve #177 to ensure documentation has the right date-time format compatible with ISO8601.
> Updates to Abbreviated format GH Issue #177

- doc/md_src_files/040_stakeholders-scope.md
- doc/md_src_files/060_decision-trees.md
As per the suggestion of @j--- I'm suggesting this to resolve #235.
> Updating text to conform to Human Impact change

- doc/md_src_files/030_representingInformation.md
> Address time-sensitivity of some decision points

- doc/md_src_files/040_stakeholders-scope.md
- doc/md_src_files/080_workedExample.md
Happened to stumble on two small typo's after last update.
> Two small typo fixes

- doc/md_src_files/05_01_exploitation.md
- doc/md_src_files/12_related_systems.md
- doc/md_src_files/sources_ssvc.bib
To close #198 
Updated the /bib file
corrected typo
updated the EPSS section.
> EPSS changes

- doc/md_src_files/05_07_mission_impact.md
- doc/md_src_files/sources_ssvc.bib
These changes/additions express the DoD's concept of Mission Essential Functions, which is a slightly different use case than FEMA's which is what we original presumed.
> Mention DoD 3020.26 MEF definition in Mission Impact

- doc/md_src_files/16_acknowledgements.md
- doc/pdf-styling.yaml
Resolves discussion #280 
Fixes #297
> update authors, ack previous authors

- docs/tutorials/index.md
This is a small PR to fix a broken link (the video url changed)
> Fix video links

- data/schema/Decision_Point.schema.json
- data/schema/Decision_Point_Group.schema.json
This is just the json schema portion of what was in #328. Creating this as a separate PR to keep the JSON changes isolated.
- Resolves #321
> Add new json schemas for decision points and dp groups

- src/ssvc/outcomes/groups.py
> Add OutcomeGroup for CISA's customized version of SSVC

- docs/reference/decision_points/human_impact.md
Looking at the limited discussion from the ticket, just made a few changes:
- Moved the comment about "we changed this from a previous version" as a footnote in regards to how this is a compound decision to make it less confusing for people who don't know the history of SSVC
- Then just moved up the description that I thought was helpful to be a part of the introduction up.
Not sure if there's anything else content wise that we want added, but this cleans it up a bit at least. Let me know if there's anything specific to be added!
> Human impact change proposal

- docs/adr/0011-automatable-and-value-density-and-CVSSv4.md
- docs/adr/index.md
> add initial draft of ADR

- docs/ssvc-calc/css.css
- docs/ssvc-calc/ssvc.js
Resolves #514  display issues
1. Ensure all the popup help screens remain visible
2. Given an option to hide "Jarring" help text with a checkbox "Hide help text"
Review the updated SSVC Calculator at https://sei-vsarvepalli.github.io/SSVC/ssvc-calc/
> SSVC calculator display updates for iframe

- docs/index.md
- docs/topics/items_with_same_priority.md
This should be the correct fixed branch with only the WIP disclaimer being removed. 
- resolves #494
> Remove WIP disclaimer from home page

- CONTRIBUTING.md
- LICENSE
> Fix license link in CONTRIBUTING.md

- data/schema/v1/Decision_Point_Value_Selection-1-0-1.schema.json
- requirements.txt
Publish schema fix from
- #633
> Schema fix

- data/schema/v1/Decision_Point_Value_Selection-1-0-1.schema.json
- requirements.txt
This PR catches public up to main
- Json schema changes in #642 
- Misc dependabot updates since last merge
> Publish JSON schema base change to 2020-12

- doc/md_src_files/sources_ssvc.bib
> Update FEMA Federal continuity directive link

- data/schema/v1/Decision_Point-1-0-1.schema.json
- data/schema/v1/Decision_Point_Group-1-0-1.schema.json
- data/schema/v1/Decision_Point_Value_Selection-1-0-1.schema.json
- data/schema/v1/Outcome_Group-1-0-1.schema.json
- src/ssvc/_mixins.py
- src/ssvc/namespaces.py
- src/test/test_mixins.py
An attempt to resolve #764  and help with inconsistent spaces and tabs.
> Update namespace to ensure sufficient limits are established

- data/schema/v2/Decision_Point_Value_Selection-2-0-0.schema.json
- src/ssvc/selection.py
- src/test/test_selections.py
Specifically to resolve #905 issue and help with CSAF integration.
> Update CVE items to be unique and update tests see #905

- .github/dependabot.yml
Update dependabot config to use uv ecosystem
> Update Dependabot config to use uv
